#!/home/chad/anaconda/bin/python

from pymongo import MongoClient

dbname	="geo"
colname	='panoramio'

client	=MongoClient()
db		=client[dbname]
col		=db[colname]

csvfilename	='europe.csv'
lines	=open(csvfilename).readlines()
header	=lines[0].strip().split()
values	=[x.strip().split() for x in lines[1:]]

documents	=[dict(zip(header,val)) for val in values]

failed	=0
success	=0
for i,doc in enumerate(documents):
	doc['_id']	=doc['photo_id']
	try:
		col.insert(doc)
		success	=success+1
	except:
		failed	=failed+1
	print "success %6i failed %6i \r"%(success,failed),
