#!/home/chad/anaconda/bin/python
import	numpy as np
import	matplotlib.pyplot as plt
import	sys
import	urllib2
import	urllib
import	json
import	pickle
import	random
import	requests
import	glob

def	readCSV(filename,images):
	photos	=[x.split()[3] for x in open(filename).readlines()[31870:]]
	for i,photo in enumerate(photos):
		url		=photo
		name	='images/'+photo.split('/')[-1]
		if name not in images:
			urllib.urlretrieve(url,name)
			print '%6i %20s %s'%(i,name,url)

def	readFolder(foldername):
	images	=set(glob.glob(foldername+'/*'))
	return images

q	=readFolder('images')
readCSV('test2.csv',q)
